apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-client
    spec:
      containers:
        - name: config-client
          image: k8s-registry.xxx.local/baseplatform/config-client:v1
          env:
            - name: AUTHOR
              value: config-client
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: config-client
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: config-client