server:
  servlet:
    context-path: /uaa
spring:
  application:
    name: oauth-server
  cloud:
    config:
      uri: http://localhost:8762/
      profile: ${env:local}
      name: ${spring.application.name},global
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: liuqi
  profiles:
    active: ${env:local}

#安全配置
security:
  oauth2:
    client:
      #令牌端点
      access-token-uri: http://localhost:8764/uaa/oauth/token
      user-authorization-uri: http://localhost:8764/uaa/oauth/authorize
      #授权
      client-id: ${spring.application.name}
      client-secret: secret
    resource:
      jwt:
        key-value: springcloud123

