server:
  port: 8012
spring:
  application:
    name: provider-user
    jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://bone:123456@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true #优先使用IP地址进行注册
    leaseExpirationDurationInSeconds: 15 #Eureka Client间隔多久向Eureka Server发送心跳,告知Eureka Server自己还存活,默认90
    leaseRenewalIntervalInSeconds: 5 #Eureka Client向Eureka Server发送心跳的时间间隔,默认30